[package]
name = "sharpie"
version = "1.0.0-alpha.1"
edition = "2021"

[dependencies]
bitflags = {version = "2.8.0", features = ["serde"]}
derive_builder = "0.20.2"
num-format = "0.4.4"
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.138"

