#!/bin/bash

sed_filter() {
    sed '
        /^[[:space:]]*$/d
        s/[[:blank:]][[:blank:]]*/ /g
        s/^[[:blank:]]*//
        s/[[:space:]]*$//
        s/\.00*//g
        '
}

ship=$1
report=${ship%.sship}.report

if [ -z "$ship" ]; then
    echo "Usage: $0 SHIP.sship" >&2
    exit 1
elif ! [ -f "$ship" ]; then
    echo "SpringSharp ship not found: $ship" >&2
    exit 1
elif ! [ -f "$report" ]; then
    echo "SpringSharp report not found: $report" >&2
    exit 1
fi

diff="$(command -p diff) -y"
command -v vimdiff >/dev/null && diff=vimdiff

$diff <(cargo run -- convert -r "$ship" | sed_filter) \
      <(sed_filter < "$report")
